apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}-service
  namespace: {{ .Values.namespace }}

spec:
  selector:
    app: {{ .Values.serviceName }}

  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}

  type: {{ .Values.service.type }}